"""Tests for artifact generation."""

from pathlib import Path

import pytest

from chat_retro.artifacts import ArtifactGenerator


class TestArtifactGenerator:
    """Test ArtifactGenerator class."""

    @pytest.fixture
    def generator(self, tmp_path: Path) -> ArtifactGenerator:
        """Create generator with temp output directory."""
        return ArtifactGenerator(output_dir=tmp_path / "outputs")

    def test_generate_html_basic(self, generator: ArtifactGenerator):
        """Generate basic HTML without D3."""
        html = generator.generate_html(
            title="Test Report",
            data={"patterns": []},
            include_d3=False,
        )

        assert "<!DOCTYPE html>" in html
        assert "<title>Test Report</title>" in html
        assert '"patterns": []' in html

    def test_generate_html_includes_d3(self, generator: ArtifactGenerator):
        """HTML includes D3.js when requested."""
        html = generator.generate_html(
            title="Test",
            data={},
            include_d3=True,
        )

        # Should include D3 library or fallback message
        assert "d3" in html.lower() or "D3.js" in html

    def test_generate_html_self_contained(self, generator: ArtifactGenerator):
        """HTML has no external network requests."""
        html = generator.generate_html(
            title="Test",
            data={"test": "data"},
            include_d3=True,
        )

        # Check that there are no external resource references
        # (src= or href= pointing to external URLs would cause network requests)
        assert 'src="http' not in html, "External script src found"
        assert 'href="http' not in html, "External stylesheet href found"
        assert "<link " not in html or 'rel="stylesheet"' not in html, "External stylesheet link found"

    def test_generate_html_with_visualization_code(self, generator: ArtifactGenerator):
        """HTML includes custom visualization code."""
        viz_code = "console.log('test');"
        html = generator.generate_html(
            title="Test",
            data={},
            visualization_code=viz_code,
        )

        assert viz_code in html

    def test_generate_html_includes_timestamp(self, generator: ArtifactGenerator):
        """HTML includes generation timestamp."""
        html = generator.generate_html(title="Test", data={})

        assert "Generated:" in html

    def test_generate_html_escapes_data(self, generator: ArtifactGenerator):
        """Data is properly JSON-encoded."""
        html = generator.generate_html(
            title="Test",
            data={"text": "Hello \"world\""},
        )

        # Should be properly escaped
        assert 'Hello \\"world\\"' in html or 'Hello "world"' in html

    def test_generate_markdown_basic(self, generator: ArtifactGenerator):
        """Generate basic markdown."""
        md = generator.generate_markdown(
            title="Test Report",
            content="Some analysis content.",
        )

        assert "# Test Report" in md
        assert "Some analysis content." in md
        assert "Generated by chat-retro" in md

    def test_generate_markdown_with_metadata(self, generator: ArtifactGenerator):
        """Markdown includes frontmatter when metadata provided."""
        md = generator.generate_markdown(
            title="Test",
            content="Content",
            metadata={"type": "reflection", "patterns": ["a", "b"]},
        )

        assert "---" in md
        assert "type: reflection" in md
        assert '["a", "b"]' in md

    def test_save_html_creates_file(self, generator: ArtifactGenerator, tmp_path: Path):
        """save_html creates output file."""
        path = generator.save_html(
            filename="test-report",
            title="Test",
            data={"test": True},
        )

        assert path.exists()
        assert path.suffix == ".html"
        assert "<!DOCTYPE html>" in path.read_text()

    def test_save_html_creates_directory(self, generator: ArtifactGenerator):
        """save_html creates output directory if needed."""
        assert not generator.output_dir.exists()

        generator.save_html(
            filename="test",
            title="Test",
            data={},
        )

        assert generator.output_dir.exists()

    def test_save_markdown_creates_file(
        self, generator: ArtifactGenerator, tmp_path: Path
    ):
        """save_markdown creates output file."""
        path = generator.save_markdown(
            filename="reflection",
            title="Monthly Reflection",
            content="Analysis here.",
        )

        assert path.exists()
        assert path.suffix == ".md"
        assert "# Monthly Reflection" in path.read_text()

    def test_html_works_from_file_protocol(
        self, generator: ArtifactGenerator, tmp_path: Path
    ):
        """Generated HTML should work when opened as local file.

        This test verifies the structure is correct for file:// usage.
        Actual rendering would require a browser.
        """
        path = generator.save_html(
            filename="local-test",
            title="Local Test",
            data={"message": "Hello"},
            visualization_code="document.getElementById('visualization').textContent = DATA.message;",
        )

        html = path.read_text()

        # All scripts should be inline, not external
        assert '<script src="' not in html
        # All styles should be inline
        assert '<link rel="stylesheet"' not in html
        # Should have the visualization div
        assert 'id="visualization"' in html


class TestD3Bundling:
    """Test D3.js bundling."""

    def test_d3_is_bundled(self):
        """D3.js file exists in assets."""
        asset_path = Path(__file__).parent.parent / "src" / "chat_retro" / "assets" / "d3.v7.min.js"
        assert asset_path.exists(), "D3.js should be bundled in assets/"

    def test_d3_loads_correctly(self):
        """D3.js loads without error."""
        generator = ArtifactGenerator()
        d3_code = generator._load_d3_js()

        # Should be substantial content
        assert len(d3_code) > 100000, "D3.js should be ~280KB"
        # Should start with D3 license comment
        assert "d3js.org" in d3_code or "Mike Bostock" in d3_code
